### ISSUE TITLE
create.ps errors on attempted problemset creation for the first time

### ISSUE THREAD

**Issue by kmishra9** [skranz/RTutor#15]
Hi there,

I'm trying to generate a new problemset using `create.ps` to no avail. Specifically, I'm getting the following error:
`Error in eval(base::parse(text = code, srcfile = NULL)) : object 'setup' not found`

[This is the file](https://pastebin.com/zSNtc6Wt) I'm using to generate the problemset, if its helpful as a reference. I can also confirm that create.ps works on the Example_sol.Rmd file linked in [this vignette](https://github.com/skranz/RTutor/blob/master/vignettes/Guide_for_Developing_Interactive_R_Problemsets.md).

**Comment by skranz** [comment]
I posted [here](https://pastebin.com/index/zSNtc6Wt) a modified version of your problem set that now works on my computer (to test it, you need to adapt the working directory again).
There are two changes:

1. The setup chunk uses a quoted chunk name
        ```{r "setup", include=FALSE}
    Admittedly, it is a bit annoying that RTutor requires the quotes for chunk names and otherwise throws an error. I will try to fix that issue in a newer version.

2. The call to `create.ps` gets the additional argument `addons = "quiz"`. Otherwise, it won't be able to parse your quiz blocks.

Can you try out, whether that works on your computer?

**Comment by kmishra9** [comment]
Hmm, so when I follow the link you posted, it's actually just the exact same link I posted, so I think you might've accidentally forgot to copy the new link to your clipboard.

However, I implemented the two fixes you mentioned myself and ran the new "setup" chunk again. I got this error:
```
Error: When importing quiz:
question: How many observations were there with y==0?
sc:
    - 1
    - 3
    - 5*
    - 7
    - 10
success: Great, your answer is correct!
failure: Try again.

Error : Error in yaml.load(str, handlers = handlers): could not find function "yaml.load"
```
So I imported yaml with `library(yaml)` (maybe this should be one of RTutor's dependencies in a future version?) and ran `create.ps(sol.file=sol.file, ps.name=ps.name, user.name=NULL, libs=libs, extra.code.file=NULL, var.txt.file=NULL, addons="quiz")` again. 

Unfortunately, I'm still running into issues and got the following error:
```
Quitting from lines 2-6 () 
Error in Encoding(x) : a character vector argument expected

Quitting from lines 2-6 () 
Error in Encoding(x) : a character vector argument expected

Quitting from lines 2-7 () 
Error in Encoding(x) : a character vector argument expected

Quitting from lines 2-6 () 
Error in Encoding(x) : a character vector argument expected
```

**Comment by kmishra9** [comment]
Ok so this is weird -- I didn't realize it but it's actually the case that create_ps _works_ in these sense that it generates all the files I would expect, but I do still get those "Quitting from..." errors in the console after running create_ps. 

I've plopped my code into an [RStudio Cloud project](https://rstudio.cloud/project/44954) to make sure it wasn't just my server setup so here it is if you want to play around with it and further debug what the issue might be. 

The `library(yaml)` is probably still something that should be handled from within the RTutor package though, so that's a good suggestion for your next release.

**Comment by skranz** [comment]
The error messages in `create_ps` were from code in a `try` block and everything was still created as it should be. Anyway I restructured the code a bit in the development version of RTutor (`devtools::install_github("skranz/RTutor", dep=FALSE)`) and no error is shown. I also added the `yaml` dependency (thanks for catching).

I already installed the new development version of RTutor in my original cloud project [https://rstudio.cloud/project/39040](https://rstudio.cloud/project/39040)

**Comment by skranz** [comment]
BTW: I saw that you defined your data `df` in your setup chunk. I am surprised that this seemed to have worked and I am not sure whether it will consistently work.

Normally, you should load or define data in a chunk shown to the user (need to add such a chunk at the beginning of each `## Exercise` block, even if the data was loaded in a previous exercise block).

Alternatively, you can define R objects or functions in an external .R file whose filename you pass as the argument `extra.code.file` to `create.ps`. Every object defined in that R file will be globally available in all exercises.

**Comment by kmishra9** [comment]
Got it, that's very helpful! Thanks! Unfortunately we're going to be using the Shiny app version of these apps for education so I'll be waiting on that, but creating a problemset now seems to have been handled.

**Comment by kmishra9** [comment]
I'm actually really impressed by the inclusion of that `extra.code.file` argument -- does the data passed in via the extra code file remain in the .rps binary file? We wouldn't need to supply that extra code file alongside the assignment, correct?

**Comment by skranz** [comment]
I am not 100% sure, but think that should work fine and everything should be in the rps file. You can just try out, by putting the .rps binary in a separate folder and see whether it runs fine. 

That being said, I am not sure whether it is a good idea to load large data sets in the extra.code.file. This probably will slow down a lot of things, like compiling and loading a problem set.

**Comment by kmishra9** [comment]
Annnnd, we're back. Now that we have grey screen stuffed away, I'm almost there but not quite. Something quite weird is going on here, and I think it may be RTutor rather than any number of the other variables going on. 

1. `df` seems to not be getting picked up from the prevalenceExtraCodeFile.R that you suggested earlier, in both the RMarkdown generated file, `prevalence.Rmd`, and the Shiny app generated from `prevalence_sol.Rmd`.
2. The Shiny app, once built, displays somewhat odd behavior. For example, try running that first code block -- not much happens. Try running it a few more times. When you _exit_ the Shiny app, a whole bunch of errors pop into frame + all the results of running that chunk, which is funky behavior. 

See this [new RStudio Cloud project](https://rstudio.cloud/project/46240) to replicate the issue.

**Comment by skranz** [comment]
Can you try out this project?
[https://rstudio.cloud/project/46324](https://rstudio.cloud/project/46324)

In the project, run the code in `build_prevalance.R` to build and show your problem set.

It is the same code than in the first chunk of the `prevalance_sol.Rmd` file. But strange things seem to happen now on rstudio.cloud that I have described in this issue:
[https://github.com/yihui/knitr/issues/1571](https://github.com/yihui/knitr/issues/1571)

I also fixed an unrelated bug in my RTutor version (could have arisen with a new data.table version).  and installed the newest RTutor version from Github on that Cloud project. The older RTutor version yielded an error when solving the very last chunk of the problem set.

**Comment by kmishra9** [comment]
Ok, so I can confirm that running the code in `build_prevalence.R` works to create the problemset and display the Shiny app. 

That's great, so just making sure but is there any difference in our two environments (i.e. what did you change in setting up), just so I know how to replicate it in the future? 

I created a `build_prevalence.R` file that is identical to the one in the previous project (https://rstudio.cloud/project/46240) and it runs smoothly, creating the Shiny app as desired (which is great).

**Comment by skranz** [comment]
> The very last question I have revolves around the console not "quitting" automatically when the tab with the shiny app is closed.

I created a new RTutor version that should now stop the app automatically when the window is closed. To be up-to-date with all changes just run:
```r
devtools::install_github("skranz/RTutor", dep=FALSE)
```
If you distribute a problem set to your students, I would generate a much simpler project that just contains:
1. The `.rps` file of your problem set, like `prevalance.rps`
2. A very simple R script with two lines of code like
```r
library(RTutor)
show.ps("prevalance", user.name="TestUser")
```
3. Possible data sets if your problem sets directly loads data (not neccessary if your data is included in the rps using the extra.code.file route discussed earlier)

You should definitely not let each student compile the problem set via `create.ps`, there is also no need to distribute any other files, like `prevalance_sol.Rmd`.

**Comment by kmishra9** [comment]
That's perfect -- thanks, we're really liking RTutor and will likely be using it and recommending it for several courses in Epidemiology/Biostatistics at UC Berkeley! I hope this whole exercise has helped RTutor get better as well!

**Comment by kmishra9** [comment]
I don't know if its relevant and it doesn't seem to be a functional issue that actually affects anything, but may be worth reporting:

`In readLines(sol.file) :
  incomplete final line found on 'prevalence_sol.Rmd'
`

I get this warning when I run the Shiny app from the [RStudio Cloud project](https://rstudio.cloud/project/46240) and close it -- like I said, not really an issue, but possibly something you might be interested in digging to the bottom of.

**Comment by skranz** [comment]
Indeed, while not crucial, it looks nicer without the warning. I updated a new RTutor version, where all `readLines` commands get the argument `warn=FALSE` and the warning disappears. As usual, it can be installed with
```r
devtools::install_github("skranz/RTutor", dep=FALSE)
```
Your feedback and bug reports are indeed very appreciated.

It would be great if you end up using RTutor for one or several courses in Berkeley. Please let me know when you indeed have used it for a class. That would make a nice interdisciplinary recommendation for RTutor. Also, if at some point of time in the future you decide to publicly share one or several problem sets that you use in class, I am happy to reference it on the RTutor Github page if you send me a link.

**Comment by kmishra9** [comment]
Great, thanks for that. And definitely, will do.
Some other questions/comments from people interested in working with RTutor:
1) Is there a way to automatically launch the tutorial without having to first go through an Rstudio Cloud window? I think that will be ideal for students new to coding who may find launching tutorials from commands daunting. 
2) Does Rtutor support Latex? It looks like it doesn’t based on the output of `$y$` 
3) Do the points get tabulated across students for an instructor to use for grading, or is it just for individual student self assessment?

**Comment by skranz** [comment]
Good points, which I answer in a different order.

2. RTutor does support Latex via Mathjax. Unfortunately, there seems to be a problem to compile it correctly on rstudio.cloud. I openend an issue here: 
[https://community.rstudio.com/t/markdown-markdowntohtml-does-not-correctly-handle-mathjax-on-rstudio-cloud/](https://community.rstudio.com/t/markdown-markdowntohtml-does-not-correctly-handle-mathjax-on-rstudio-cloud/)
As a work-around you could compile the problem set on your local computer and then copy the created .rps to the cloud. This then should show the Mathjax math when you run show.ps in the cloud. (At least it worked for me, using a windows notebook).
3. I now added a new feature to the newest Github version of RTutor that students can download a submission file that contains information about their solution and points (click on the download icon right to the exercise tabs). Similar as described in the end of my [blog entry](http://skranz.github.io/r/2018/06/04/RTutor_Shiny_Cloud.html) you could tell students to upload this file on some course management system and then automatically 'grade' it by adapting the script I reference in the blog.
Of course, it is always possible to cheat, so I would make the problem sets only a little bit grade-relevant, e.g. 10% of the final grade, to provide some incentives to solve them.
You should then call `create.ps` with the argument `rps.has.sol=FALSE` to avoid that students can simply extract the sample solution.
It also makes sense to call `show.ps` with the argument `auto.save.code=TRUE`. Then all changes in code by students will be automatically saved and restored when she works on the problem set again. (A student still has to rerun all chunks of an exercise, manually though). A student gets a point, if she has ever solved a task or quiz correctly. This info is stored in a file with the ending `.ups`.
If you want a more centralized, approach, you would have to run the problem sets on your own shiny server. I started an incomplete vignette [here](https://github.com/skranz/RTutor/blob/master/vignettes/Hosting%20RTutor%20Problem%20Sets%20on%20a%20Web%20Server.Rmd). For the server version, you can also have a teacher app, where you directly see the grades. Unfortunately, the RAppArmor approach does not easily work together with docker and since I am no security expert, I cannot guarantee that it is 100% secure.

1. The only way I currently see is to host it in your own server or on shinyapps.io, which have other drawbacks discussed earlier.  At some point I would just tell students that they go to university, not to kindergarden. Even if a student finds it at first daunting to open a file, select two lines of code and press a run button, how hard is to replicate these steps if you give them a manual? (It may be a bit inconvenient to run the script each time, but I don't think much time is lost).
