### ISSUE TITLE
Running example chunk

### ISSUE THREAD

**Issue by bernard-liew** [skranz/RTutor#19]
Hi,

When running this example chunk 
```
    ```{r "setup"}
    library(RTutor)
    setwd(getwd())
    ps.name = "myps"; sol.file = paste0(ps.name,"_sol.Rmd")
    libs = c("ggplot2") # character vector of all packages you load in the problem set

    #name.rmd.chunks(sol.file)
    create.ps(sol.file=sol.file, ps.name=ps.name, libs=libs)
              
    # The following line directly shows the problem set 
    # in the browser
    show.ps(ps.name,launch.browser=TRUE,
      auto.save.code=FALSE,sample.solution=FALSE)

    ```
```

`create.ps(sol.file=sol.file, ps.name=ps.name, libs=libs)`

threw an error of 

Error in cdt[ci, ] : incorrect number of dimensions

Regards,
Bernard

**Comment by skranz** [comment]
Hard to say what is wrong without seeing the whole file. Could you post or send me via email the whole code of your `myps_sol.Rmd` file? 

Side remark: For getting started it might generally be good to copy one of the files in the `inst/examples` directory like

https://raw.githubusercontent.com/skranz/RTutor/master/inst/examples/Example_sol.Rmd

**Comment by braunsb** [comment]
I have the same error. It's in line 88 of te.to.rps(). I'll try another example. I'm trying to decide between this & learnr and I'll go with whatever works. But I like your design a lot. 

Here is my file, but I couldn't upload it as an rmd (GitHub rejected it). If you change the extension from txt to rmd you should have the same as my file "myps_sol.rmd). Thanks for any help.
[myps_sol.txt](https://github.com/skranz/RTutor/files/3718962/myps_sol.txt)

**Comment by skranz** [comment]
Thanks a lot for the example file. When I run `create.ps` it, I got the error message 
```
Error in cdt[ci, ] : incorrect number of dimensions
```
Did you get the same? I think the problem is that RTutor did not detect your exercises, because you have put a tab before all of your code. I updated the RTutor version on Github (not yet on my drat repositorium) and it now gives a more informative error message if no exercise is detected:

```
Error in te.to.rps(te = te) : 
I could not find any exercise in your solution file. 
An exercise must start with a new line starting EXACTLY with 
      
## Exercise YOUREXNAME

(no spaces or tabs before the ##).
You can pick some name or number for YOUREXNAME or
use a short and long name separated by two dashes, like '1 -- My first exercise'.
```
Also all other blocks starting with `#<` don't accept a tab or space before the `#<`. Does your problem disappear once you remove the tab before all of your code?

BTW: To use the quiz you have to add the argument `addons="quiz"` in your call to `create.ps`.

**Comment by braunsb** [comment]
Hi, and thanks for the response. That is the exact error message I got.

All I'm trying to do is run your example. I didn't put tabs anywhere; I just copied your code into a Markdown file in RStudio. And the code probably doesn't detect an exercise because I haven't written any. I'm just running what you supplied. 

In the spirit of helpfulness, I will say this: I am pretty excited about all the good stuff that's possible with your package. But I followed the exact instructions, got an error, and then found out that following those instructions means I did the wrong thing. My confidence is at a low ebb. And I don't have time to go through getting rid of tabs. This package needs to work in an RStudio Markdown file, the first time, without me putting any time into editing code I copied from your GitHub to see an example, or I can't commit to it. 

I hope you hear that as helpful, because that is how I mean it. I'd like to see you succeed. 

Suggestions for me finding an easy way forward? Thanks!

**Comment by skranz** [comment]
Ok, I now finally see the problem. I actually never tested to copy paste the example code from http://skranz.github.io/RTutor/articles/01_RTutorOverview.html even though I stated that one should do this. I thought what could possible go wrong there...

Well, embarassingly copy-pasting did indeed not work, because that code had 4 spaces at the beginning of each line. (This is due to the fact that it is not straightforward to have an Rmd file that shows Rmd code examples).

I now explicitly state not to copy paste from the HTML but provide an explicit link to a raw example file on Github. (On the web version I was even able to remove the trouble causing leading spaces, but not in the vignettes, which will be automatically compiled). I hope it now works fine with the updated documentation. Please let me know if it doesn't and thanks to both of you for making me aware of this issue.
