### ISSUE TITLE
Test that would allow open text

### ISSUE THREAD

**Issue by djourd1** [skranz/RTutor#20]
This is not really an issue, but a question. 

I would like to write a task where students should comment in a free (but limited) text  their results, for example ask them to comment what they deduct from the graph.  So that would be a text that is not checked for right or wrong, but something that would be saved when students send their results.  This would be an open text (not some code)

Is there a way to do this?

**Comment by skranz** [comment]
This is not a feature of RTutor, but there is a workaround.

Let me first write what you can do if students **solve the problem set in RStudio** (not in the webbrowser). You can just ask them two write their answer somewhere in the Rmd file.

You get the code of a students Rmd file as following. You can manually load a submission file that was generated with `make.submission`  via `sub=load.submission(filename)`.

`sub` is an R environment. You access the Rmd text by `sub$rmd.code`. It is best if you somehow mark the place where students write their answer with a header and footer line, so that you can write a short program that extracts the answers, e.g. like

```
--- Answer 1 

Write your answer here.

--- End Answer 1
```

**Comment by skranz** [comment]
If you create **shiny based problem sets** that run in the browser it is a bit more complex. First, of all students should always show the problem set using the argument `auto.save.code=TRUE` in their call to `show.ps`. (You should always set this option anyway if students solve shiny based problem sets at home and shall submit their solution.)

You can create a chunk in which students should write their solution into an R string and make a custom test that always evaluates `TRUE`. For example as here:

```
  Write your answer text inside the quotes "" as an R String and press `Check`.
  (Note that you always see afterwards the message "Great, solved correctly."
   But your answer will in fact be graded after you submit your problem set.)
  
  ```{r results='hide'}
  #< task_notest
  "
  Insert your answer here in those quotes
  
  
  
  
  
  "
  #>
  ""
  #< test
  holds.true(TRUE)
  #>
```
When you load a submission file `sub=load.submission(filename)`, you should find the student's code for every chunk in `sub$cu$stud.code`. I have not fully tested whether the code is always there, but I it works robustly.

**Comment by djourd1** [comment]
I tried the second solution. It does not throw any error, but when I launch the browser, that test does not show ...  I thought it was because of the results='hide' option, but it does not appear even when that option is taken out.  

We can check the code I've made at https://github.com/djourd1/RTutorLogit

**Comment by djourd1** [comment]
Sorry, I made a mistake. Just realized I forgot to close the chunk.  When closing it, it works.

**Comment by skranz** [comment]
Yeah, that was also my mistake since I omitted the closing three backticks from the example. (It is indeed somewhat tricky to include three backticks in an example in Github, since Github often recognizes it as end or start of a code section.). I hope everything works robustly. If not, please let me know.

**Comment by djourd1** [comment]
Thank you.
