### ISSUE TITLE
Controlling the width of the quizzes

### ISSUE THREAD

**Issue by djourd1** [skranz/RTutor#21]
The examples you are using for the quizzes are usually short, i.e. number.

I want the respondents to select between different longer sentences. When doing so each possible choices spans other several lines (since the width seems to be set to around 40 to 50 characters. )

Is there a command (or a way) to change this width ?

**Comment by skranz** [comment]
This can be done because you can insert into your Rmd file arbitrary HTML code. In particular, you can insert <style> blocks to change the CSS styles of HTML elements of the RTutor problem set.

Concretely, you can insert somewhere in the exercise before your quiz the HTML code:
```
<style>
.shiny-input-radiogroup {
  width: 100% !important;
}
</style>
```
Then **all** radiogroups (used for single choice quizzes) get a default width of 100%.

If you only want to adapt the width for a single quiz you should get its html id by pressing in a Chrome browser on the element with the right button and say "Inspect" ( on other browsers that may be a bit different). For example, the relevant element id for a quiz with name "myquiz" is: "addon__quiz__myquiz__part1__answer". The HTML code to change the width of that element only is:

 ```
<style>
#addon__quiz__myquiz__part1__answer {
  width: 100%;
}
</style>

**Comment by djourd1** [comment]
Both worked perfectly. Looked for multiple choice as well and discovered it was: 

```
<style>
.shiny-input-checkboxgroup  {
  width: 80% !important;
}
</style>
```

Thank you
